{% set version = '3.0.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggplot2
  version: {{ version|replace("-", "_") }}

source:
  fn: ggplot2_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggplot2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplot2/ggplot2_{{ version }}.tar.gz
  sha256: c768f5039ef684c3874a92210a975af52e74f00927ff31c31a73eb1fe139694d

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-mass
    - r-digest
    - r-gtable >=0.1.1
    - r-lazyeval
    - r-mgcv
    - r-plyr >=1.7.1
    - r-reshape2
    - r-rlang
    - r-scales >=0.5.0
    - r-tibble
    - r-viridislite
    - r-withr >=2.0.0
  run:
    - r-base
    - r-mass
    - r-digest
    - r-gtable >=0.1.1
    - r-lazyeval
    - r-mgcv
    - r-plyr >=1.7.1
    - r-reshape2
    - r-rlang
    - r-scales >=0.5.0
    - r-tibble
    - r-viridislite
    - r-withr >=2.0.0

test:
  commands:
    - $R -e "library('ggplot2')"           # [not win]
    - "\"%R%\" -e \"library('ggplot2')\""  # [win]

about:
  home: http://ggplot2.tidyverse.org, https://github.com/tidyverse/ggplot2
  license: GPL-2
  summary: A system for 'declaratively' creating graphics, based on "The Grammar of Graphics".
    You provide the data, tell 'ggplot2' how to map variables to aesthetics, what graphical
    primitives to use, and it takes care of the details.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - ocefpaf
    - daler
    - jdblischak
    - cbrueffer
