{% set version = "4.0.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggplot2
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggplot2_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggplot2/ggplot2_{{ version }}.tar.gz
  sha256: 77151025e8a17eaa043b2685421772e4e30a8a592493780f0a4583ca7b5e0ec4

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-cli
    - r-glue
    - r-gtable >=0.3.6
    - r-isoband
    - r-lifecycle >=1.0.1
    - r-rlang >=1.1.0
    - r-s7
    - r-scales >=1.4.0
    - r-vctrs >=0.6.0
    - r-withr >=2.5.0
  run:
    - r-base
    - r-cli
    - r-glue
    - r-gtable >=0.3.6
    - r-isoband
    - r-lifecycle >=1.0.1
    - r-rlang >=1.1.0
    - r-s7
    - r-scales >=1.4.0
    - r-vctrs >=0.6.0
    - r-withr >=2.5.0

test:
  commands:
    - $R -e "library('ggplot2')"           # [not win]
    - "\"%R%\" -e \"library('ggplot2')\""  # [win]

about:
  home: http://ggplot2.tidyverse.org
  dev_url: https://github.com/tidyverse/ggplot2
  license: MIT
  summary: A system for 'declaratively' creating graphics, based on "The Grammar of Graphics". You provide the data, tell 'ggplot2' how to map variables to aesthetics, what graphical primitives to use, and it takes care of the details.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
    - philip-khor
