travis:
  secure:
    BINSTAR_TOKEN: c29Dy9nx/NkGh/a0k8zeiQyd7t9j7EMOAM7YN4v2JDECE+h0mfkSxTT4Q6UFpI87aStVVaI0H97DSHOO8fCjtQAgOWTVbZDASYgWhT6BMOcmVPvgZhi8BKuQiEu2qGCyOKd+NZlmye+YlcTrCiPuMQOee18CiEUW4sqQnsjLmE/Udk3/Me9HAVECukNGkmBz+adUVMCoUc9hONJC3JJjSKlBjNIjh5ufhpuZX0iPXZAEIoUJpZRrSjJdFbUdDLsRZTo99SlQ3rdj/CUNOd9rhI9gSWVbjh4XeAAJrDrJIyBq7lZrMtVEnb9jvDsIyYKCe1bMTdp5BA2wIRcgO+oAV4Ch/s2IIdU4kAH3GbB9VMefYh5+pB0iu+LKLwCzYZs9ROMM+OVwlKdnNo6Fg5ScjIqqivDcEdBCRDepZEDzogXJC/lDbJ8naD2Lwnj3Mp1jRlzfl7NYNXyJZu1we4/hgVZN3CUyBzxbiZHjXt7KmBj/7QXannqIv57e3wqtXlmTj/9cPfzrPeLoLX+JnojpklFFaeT0Gct/tmJT4CaIvZrBJBGw05xFnMnAiyrI5KsAepdNrWfqMqbX2gG3SB5D5pj6wRP8Bz616xxeyVMvVcICivce34WtmlDz3aNqTnWjWXlJLvHpQWjp8rDIP2LwXfL20jP6PFcy17NPK+grTN8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
