appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: CsJNRF/Yk/2CN96zeP9N8ZkBGuiT0fVuBqowAmwD8b+VnJXL/OX48SFTvHHPTZVley1EO1SF3C7Rzn3lImg/dI93vUYWfs10feGY/07IUjlz7cGP0LoMv/yXO/muz/Lvuxor3bFY6hs3BAYJTljt6wBUPK8FMfq3S4MyYEYVhHo3S9d5er3+Mcyru6DHtqf6JLTT1QMS3ZbCsriA/pZgIpf75m05Mod+xFaJB6sCSDmHWfJYV6aS8NglXtdvJ2eHnL2ZyI3fkey8myf7cYkwG0r7sWMfJEID0pvojQ5bTJlUGAvidIAoMD+XrYGYrYyNpDAGdFZcuZrNldXq7v1+HQr8R4u4NHitG3u2/vYj9nm4AkKPGNA5DR5Bvyt6s0gGrS8vm9QgnoMXQaTUDf1anCc7J9j0mBg/dqEOBc7QIou6G/dMorJNj4EKPK6ZSJUX9r1O1AUQW3E3Wss7VBjRmoPIzZucoMahYmXlJ/Y2wCIzjNhXgVdG669NfedsswhmbvhqEJk/W486b5TXROGYfAm/RrCcqrqB6gFhItTW741j4vVMfBSsT7QVfBKhxmibOY0gxjjb5etZZonbdwPLCEPJB5nB6N4oYYxQnorQYpvu/FRURvhFrRtHhQWwh308VsJR2VM0Ps1RaojcJMLzOSKldcgHud3n4/ST3vUgYdk=}
